export const ProductData=[
    { id:'1', name:'Apple iPhone 14 (128 GB) ',color:'- Blue',symbol:'₹', price:'71,999', actualPrice:'M.R.P: ₹79,990', 
        offer:'(10% off)',delivery:'Free Delivery in 5 days', image:'assets/iphone14.jpg', 
        description:'Visit the Apple Store',
        description2:'Appario Retail Private Ltd', description3:'Gift-wrap available'  },
    { id:'2', name:'Apple iPhone 14 Pro (128 GB) ',color:'- Pink',symbol:'₹', price:'1,19,999', actualPrice:'M.R.P: ₹1,29,900', 
        offer:'(8% off)',delivery:'Free Delivery in 8 days',image:'assets/iphone14Pro.jpg', 
        description:'Visit the Apple Store',
        description2:'Appario Retail Private Ltd', description3:'Gift-wrap available'  },
    { id:'3', name:'Samsung Galaxy S23 Ultra 5G',color:'- Phantom Black',symbol:'₹', price:'1,34,999', actualPrice:'M.R.P: ₹1,61,999', 
        offer:'(17% off)',delivery:'Free Delivery in 9 days',image:'assets/samsungS23Ultra.jpg', 
        description:'Brand: Samsung', description1:'Samsung Galaxy S23 Ultra 5G (Phantom Black, 12GB, 512 GB Storage)',
        description2:'Appario Retail Private Ltd', description3:'Gift-wrap available'  },
    { id:'4', name:'OnePlus Buds Z2 Bluetooth ',color:'- Black',symbol:'₹', price:'4,999', actualPrice:'M.R.P: ₹5,999', 
        offer:'(16% off)',delivery:'Free Delivery in 5 days', image:'assets/oneplusbudsZ2.jpg', 
        description:'Brand: OnePlus', description1:'OnePlus Buds Z2 with Active Noise cancellation Bluetooth Headset (Obsidian Black, In the Ear)',
        description2:'Appario Retail Private Ltd', description3:'Gift-wrap available'  },
    { id:'5', name:'OnePlus Bullets Z2 Bluetooth ',color:'- Red',symbol:'₹', price:'1,999', actualPrice:'M.R.P: ₹2,299', 
        offer:'(13% off)',delivery:'Free Delivery in 5 days',image:'assets/oneplusNeckband.jpg', 
        description:'Visit the OnePlus Store', description1:'OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass, 10 Mins Charge - 20 Hrs Music, 30 Hrs Battery Life',
        description2:'Appario Retail Private Ltd', description3:'Gift-wrap available'  },
    { id:'6', name:'Caseology- Mobile Cases for iPhone 14 ',color:'',symbol:'₹', price:'1,599', actualPrice:'M.R.P: ₹2,665', 
        offer:'(40% off)',delivery:'Free Delivery in 5 days',image:'assets/iphone14Case.jpg', 
        description:'Visit the CASEOLOGY Store', description1:'CASEOLOGY by Spigen Skyfall Back  Cover Case Compatible with iPhone 14 (TPU and Polycarbonate)',
        description2:'Spigen India' , description3:'Gift-wrap available' },

    { id:'7', name:'MANQ- Men`s Slim Fit Blazer',color:' ',symbol:'₹', price:'2,249', actualPrice:'M.R.P: ₹5,999', 
        offer:'(63% off)',delivery:'Free Delivery in 4 days',image:'assets/coat.jpg', 
        description:'Visit the MANQ Store', description1:'MANQ Men`s Slim Fit Formal/Party Blazer',
        description2:'ManQ' , description3:'' },
    { id:'8', name:'Scott International- Men`s Polo ',color:' ',symbol:'₹', price:'512', actualPrice:'M.R.P: ₹1,499', 
        offer:'(66% off)',delivery:'Free Delivery in 1 day',image:'assets/tshirtMen.jpg', 
        description:'Visit the MANQ Store', description1:'MANQ Men`s Slim Fit Formal/Party Blazer',
        description2:'Switz Inc.' , description3:'Gift-wrap available' },
    { id:'9', name:'Allen Solly: Women T-Shirt ',color:' ',symbol:'₹', price:'849', actualPrice:'M.R.P: ₹1,099', 
        offer:'(23% off)',delivery:'Free Delivery in 2 days',image:'assets/tshirtWomen.jpg', 
        description:'Brand: Allen Solly', description1:'Allen Solly Women T-Shirt',
        description2:'Cocoblu Retail' , description3:'' },
    { id:'10', name:'Van Heusen- Men Trousers ',color:' ',symbol:'₹', price:'1,409', actualPrice:'M.R.P: ₹2,499', 
        offer:'(44% off)',delivery:'Free Delivery in 4 days',image:'assets/trousersMen.jpg', 
        description:'Visit the MANQ Store', description1:'Van Heusen Men Formal Trousers',
        description2:'Cocoblu Retail' , description3:'Gift-wrap available' },

    { id:'11', name:'WakeFit Wardrobe - Wooden Cupboards',color:' ',symbol:'₹', price:'16,932', actualPrice:'M.R.P: ₹23,850', 
        offer:'(20% off)',delivery:'Free Delivery in 5 days',image:'assets/Wardrobe.jpg', 
        description:'Visit the Wakefit Store', description1:'Wakefit Premier Engineered Wood Three Door Wardrobe in Regato Walnut Colour',
        description2:'RetailEZ Pvt Ltd' , description3:'' },
    { id:'12', name:'Sheesham Wood 6 Seater Dining Table Set',color:' ',symbol:'₹', price:'31,497', actualPrice:'M.R.P: ₹69,999', 
        offer:'(19% off)',delivery:'Free Delivery in 15 days',image:'assets/dining.jpg', 
        description:'Visit the MH DECOART Store', description1:'MH DECOART Solid Sheesham Wood 6 Seater Dining Table Set with 4 Chair & 1 Bench with Base Cushion',
        description2:'MH Decoart' , description3:'' },
    { id:'13', name:'SM ARTS Solid Sheesham Sofa Set',color:' ',symbol:'₹', price:'27,499', actualPrice:'M.R.P: ₹50,398', 
        offer:'(45% off)',delivery:'Free Delivery in 14 days',image:'assets/sofaSet.jpg', 
        description:'Visit the MANQ Store', description1:'SM ARTS Solid Sheesham Sofa Set 5 Seater | Wooden Sofa Set 3+1+1',
        description2:'Sold and Fulfilled by Shree Maruti Arts' , description3:'' },
    { id:'14', name:'HomeTown Alex King Size Engineered Bed',color:' ',symbol:'₹', price:'23,967', actualPrice:'M.R.P: ₹28,695', 
        offer:'(16% off)',delivery:'Free Delivery in 15 days',image:'assets/beds.jpg', 
        description:'Brand: HomeTown', description1:'HomeTown Alex King Size Engineered Wood Bed with Storage (Textured Finish, Dark Walnut)',
        description2:'RetailEZ Pvt Ltd' , description3:'' },

];

// export const addToCart="Add To Cart"